### ISSUE TITLE
Crash while loading firefox.com: webrender/src/batch_builder.rs:149

### ISSUE THREAD

**Issue by paulrouget** [glennw/webrender#155]
It used to work.

```
thread '<unnamed>' panicked at 'assertion failed: clipped_pos_rect.size.width.fract() == 0.0', /Users/paul/git/servo-webrender/../webrender/src/batch_builder.rs:149
stack backtrace:
   1:        0x107f9ebb8 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x107fa0daf - panicking::default_handler::_<closure>::closure.41800
   3:        0x107fa082f - panicking::default_handler::haa11ce011d688073GWx
   4:        0x107f8b9b4 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x1072ed5c4 - sys_common::unwind::begin_unwind::h13565596160845807443
   6:        0x1072f0244 - batch_builder::BatchBuilder<'a>::add_complex_clipped_rectangle::hebf281d23e314c0817a
   7:        0x107337d8b - node_compiler::AABBTreeNode.NodeCompiler::compile::hf0a692f303e5ee6eA5n
   8:        0x107336ebf - F.FnBox::call_box::h8589827017861732960
   9:        0x10761d650 - sys_common::unwind::try::try_fn::h12873994005467651312
  10:        0x107f9dff8 - __rust_try
  11:        0x107f9aeae - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  12:        0x10761ffc2 - boxed::F.FnBox<A>::call_box::h14464300662002536950
  13:        0x107f9fecd - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  14:     0x7fff9b6a799c - _pthread_body
  15:     0x7fff9b6a7919 - _pthread_start
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:688
stack backtrace:
   1:        0x107f9ebb8 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x107fa0daf - panicking::default_handler::_<closure>::closure.41800
   3:        0x107fa082f - panicking::default_handler::haa11ce011d688073GWx
   4:        0x107f8b9b4 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x107f8be5e - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x107f9e1d7 - rust_begin_unwind
   7:        0x107fc5740 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x107625e71 - Scope<'pool, 'scope>::join_all::h2ee880d8cd87cb45aga
   9:        0x10732c6a4 - frame::Frame::build::h2b3f03710f0c3e00snk
  10:        0x10737f575 - render_backend::RenderBackend::render::hb46ccf1c5ac5f41bgVo
  11:        0x10734b342 - render_backend::RenderBackend::run::hef23f9f4d0176fdarLo
  12:        0x10739e9b4 - sys_common::unwind::try::try_fn::h4037959654079087717
  13:        0x107f9dff8 - __rust_try
  14:        0x107f9aeae - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  15:        0x10739fafa - boxed::F.FnBox<A>::call_box::h4080903807828173708
  16:        0x107f9fecd - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  17:     0x7fff9b6a799c - _pthread_body
  18:     0x7fff9b6a7919 - _pthread_start
thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) }', ../src/libcore/result.rs:688
stack backtrace:
   1:        0x107f9ebb8 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x107fa0daf - panicking::default_handler::_<closure>::closure.41800
   3:        0x107fa082f - panicking::default_handler::haa11ce011d688073GWx
   4:        0x107f8b9b4 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x107f8be5e - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x107f9e1d7 - rust_begin_unwind
   7:        0x107fc5740 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x107789549 - api::RenderApi::add_display_list::h9c8dff3db95ad97bJHb
   9:        0x106a33da6 - webrender_helpers::StackingContext.WebRenderStackingContextConverter::convert_to_webrender::hf65854b25150004bOdx
  10:        0x106aa35f3 - webrender_helpers::DisplayItem.WebRenderDisplayItemConverter::convert_to_webrender::h8049ad97dde53199nhx
  11:        0x106aa226f - webrender_helpers::Box<DisplayList>.WebRenderDisplayListConverter::convert_to_webrender::hf7e8dec913d33989nfx
  12:        0x106a33d57 - webrender_helpers::StackingContext.WebRenderStackingContextConverter::convert_to_webrender::hf65854b25150004bOdx
  13:        0x106aa35f3 - webrender_helpers::DisplayItem.WebRenderDisplayItemConverter::convert_to_webrender::h8049ad97dde53199nhx
  14:        0x106aa226f - webrender_helpers::Box<DisplayList>.WebRenderDisplayListConverter::convert_to_webrender::hf7e8dec913d33989nfx
  15:        0x106a33d57 - webrender_helpers::StackingContext.WebRenderStackingContextConverter::convert_to_webrender::hf65854b25150004bOdx
  16:        0x106aa35f3 - webrender_helpers::DisplayItem.WebRenderDisplayItemConverter::convert_to_webrender::h8049ad97dde53199nhx
  17:        0x106aa226f - webrender_helpers::Box<DisplayList>.WebRenderDisplayListConverter::convert_to_webrender::hf7e8dec913d33989nfx
  18:        0x106a33d57 - webrender_helpers::StackingContext.WebRenderStackingContextConverter::convert_to_webrender::hf65854b25150004bOdx
  19:        0x106aa35f3 - webrender_helpers::DisplayItem.WebRenderDisplayItemConverter::convert_to_webrender::h8049ad97dde53199nhx
  20:        0x106aa226f - webrender_helpers::Box<DisplayList>.WebRenderDisplayListConverter::convert_to_webrender::hf7e8dec913d33989nfx
  21:        0x106a33d57 - webrender_helpers::StackingContext.WebRenderStackingContextConverter::convert_to_webrender::hf65854b25150004bOdx
  22:        0x106aa35f3 - webrender_helpers::DisplayItem.WebRenderDisplayItemConverter::convert_to_webrender::h8049ad97dde53199nhx
  23:        0x106aa226f - webrender_helpers::Box<DisplayList>.WebRenderDisplayListConverter::convert_to_webrender::hf7e8dec913d33989nfx
  24:        0x106a33d57 - webrender_helpers::StackingContext.WebRenderStackingContextConverter::convert_to_webrender::hf65854b25150004bOdx
  25:        0x106aa35f3 - webrender_helpers::DisplayItem.WebRenderDisplayItemConverter::convert_to_webrender::h8049ad97dde53199nhx
  26:        0x106aa226f - webrender_helpers::Box<DisplayList>.WebRenderDisplayListConverter::convert_to_webrender::hf7e8dec913d33989nfx
  27:        0x106a33d57 - webrender_helpers::StackingContext.WebRenderStackingContextConverter::convert_to_webrender::hf65854b25150004bOdx
  28:        0x106a8f0bf - layout_thread::LayoutThread::perform_post_main_layout_passes::h2432abf606c57c67Ear
  29:        0x106a04db4 - layout_thread::LayoutThread::perform_post_style_recalc_layout_passes::h6a718355ed85f0c147q
  30:        0x1069d73ae - layout_thread::LayoutThread::handle_request::hc16ed0d4edae377fhmq
  31:        0x10699f8ca - sys_common::unwind::try::try_fn::h10583997351341377314
  32:        0x107f9dff8 - __rust_try
  33:        0x107f9aeae - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  34:        0x1069a084a - boxed::F.FnBox<A>::call_box::h7559661375126348099
  35:        0x107f9fecd - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  36:     0x7fff9b6a799c - _pthread_body
  37:     0x7fff9b6a7919 - _pthread_start
thread 'PaintThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:688
stack backtrace:
thread 'LayoutWorker worker 2/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:688
thread 'LayoutWorker worker 3/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:688
thread 'LayoutWorker worker 1/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:688
   1:        0x107f9ebb8 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
thread 'Constellation' panicked at 'unable to find pipeline - this is a bug', ../src/libcore/option.rs:298
   2:        0x107fa0daf - panicking::default_handler::_<closurethread 'PaintThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) }', ../src/libcore/result.rs:688
>::closure.41800
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:688
   3:        0x107fa082f - panicking::default_handler::haa11ce011d688073GWx
   4:        0x107f8b9b4 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x107f8be5e - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x107f9e1d7 - rust_begin_unwind
   7:        0x107fc5740 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x1071cbfcb - paint_thread::PaintThread<C>::start::h8891479371392591342
   9:        0x1071bef22 - sys_common::unwind::try::try_fn::h12919057137521718273
  10:        0x107f9dff8 - __rust_try
thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) }', ../src/libcore/result.rs:688
  11:        0x107f9aeae - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  12:        0x1071bfa0a - boxed::F.FnBox<A>::call_box::h15390661390261453747
  13:        0x107f9fecd - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  14:     0x7fff9b6a799c - _pthread_body
  15:     0x7fff9b6a7919 - _pthread_start
stack backtrace:
thread 'thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:688
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:688
PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:688
   1:        0x107f9ebb8 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x107fa0daf - panicking::default_handler::_<closure>::closure.41800
   3:        0x107fa082f - panicking::default_handler::haa11ce011d688073GWx
   4:        0x107f8b9b4 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x107f8be5e - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x107f9e1d7 - rust_begin_unwind
   7:        0x107fc5740 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x1069c4eec - sys_common::unwind::try::try_fn::h17384109164497557634
   9:        0x107f9dff8 - __rust_try
  10:        0x107f9aeae - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  11:        0x1069c5e77 - boxed::F.FnBox<A>::call_box::h2582450649537092597
  12:        0x107f9fecd - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  13:     0x7fff9b6a799c - _pthread_body
  14:     0x7fff9b6a7919 - _pthread_start
stack backtrace:
   1:        0x107f9ebb8 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x107fa0daf - panicking::default_handler::_<closure>::closure.41800
   3:        0x107fa082f - panicking::default_handler::haa11ce011d688073GWx
   4:        0x107f8b9b4 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x107f8be5e - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x107f9e1d7 - rust_begin_unwind
   7:        0x107fc5740 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x1069c4eec - sys_common::unwind::try::try_fn::h17384109164497557634
   9:        0x107f9dff8 - __rust_try
  10:        0x107f9aeae - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  11:        0x1069c5e77 - boxed::F.FnBox<A>::call_box::h2582450649537092597
  12:        0x107f9fecd - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  13:     0x7fff9b6a799c - _pthread_body
  14:     0x7fff9b6a7919 - _pthread_start
stack backtrace:
   1:        0x107f9ebb8 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x107fa0daf - panicking::default_handler::_<closure>::closure.41800
   3:        0x107fa082f - panicking::default_handler::haa11ce011d688073GWx
   4:        0x107f8b9b4 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x107f8be5e - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x107f9e1d7 - rust_begin_unwind
   7:        0x107fc5740 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x1069c4eec - sys_common::unwind::try::try_fn::h17384109164497557634
   9:        0x107f9dff8 - __rust_try
  10:        0x107f9aeae - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  11:        0x1069c5e77 - boxed::F.FnBox<A>::call_box::h2582450649537092597
  12:        0x107f9fecd - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  13:     0x7fff9b6a799c - _pthread_body
  14:     0x7fff9b6a7919 - _pthread_start
stack backtrace:
   1:        0x107f9ebb8 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x107fa0daf - panicking::default_handler::_<closure>::closure.41800
   3:        0x107fa082f - panicking::default_handler::haa11ce011d688073GWx
   4:        0x107f8b9b4 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x107f8be5e - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x107f9e1d7 - rust_begin_unwind
   7:        0x107fc5740 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x106896017 - constellation::Constellation<LTF, STF>::handle_failure_msg::h6719814148374464005
   9:        0x106814c9e - constellation::Constellation<LTF, STF>::handle_request::h12398965808278059948
  10:        0x1067ffbe7 - export::compositing::constellation::Constellation<LTF, STF>::start::_<closure>::closure.23898
  11:        0x1067ff489 - sys_common::unwind::try::try_fn::h7098318269982728237
  12:        0x107f9dff8 - __rust_try
  13:        0x107f9aeae - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  14:        0x1068012fa - boxed::F.FnBox<A>::call_box::h17544099623018493435
  15:        0x107f9fecd - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  16:     0x7fff9b6a799c - _pthread_body
  17:     0x7fff9b6a7919 - _pthread_start
stack backtrace:
   1:        0x107f9ebb8 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x107fa0daf - panicking::default_handler::_<closure>::closure.41800
   3:        0x107fa082f - panicking::default_handler::haa11ce011d688073GWx
   4:        0x107f8b9b4 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x107f8be5e - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x107f9e1d7 - rust_begin_unwind
   7:        0x107fc5740 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x1071bf4fb - sys_common::unwind::try::try_fn::h12919057137521718273
   9:        0x107f9dff8 - __rust_try
  10:        0x107f9aeae - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  11:        0x1071bfa0a - boxed::F.FnBox<A>::call_box::h15390661390261453747
  12:        0x107f9fecd - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  13:     0x7fff9b6a799c - _pthread_body
  14:     0x7fff9b6a7919 - _pthread_start
stack backtrace:
   1:        0x107f9ebb8 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x107fa0daf - panicking::default_handler::_<closure>::closure.41800
   3:        0x107fa082f - panicking::default_handler::haa11ce011d688073GWx
   4:        0x107f8b9b4 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x107f8be5e - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x107f9e1d7 - rust_begin_unwind
   7:        0x107fc5740 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x106e90fed - dom::node::OpaqueStyleAndLayoutData::dispose::he573f803fd4d198fbzZ
   9:        0x106e911c7 - dom::node::Node::teardown::h80d4b050be947b38aKZ
  10:        0x106e912c9 - dom::node::Node::teardown::h80d4b050be947b38aKZ
  11:        0x106f44b1b - dom::window::Window::clear_js_runtime::h8c654f127cca3d7diic
  12:        0x106fd6ebd - script_thread::shut_down_layout::h43b108923ec0ed98jIi
  13:        0x106fba187 - script_thread::ScriptThread::handle_msgs::_<closure>::closure.169574
  14:        0x106fa2ebf - script_thread::ScriptThread::handle_msgs::h42902ccbeb26d4284nh
  15:        0x106f6a257 - sys_common::unwind::try::try_fn::h6700430166590279951
  16:        0x107f9dff8 - __rust_try
  17:        0x107f9aeae - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  18:        0x106f6bce1 - boxed::F.FnBox<A>::call_box::h4377540654281972257
  19:        0x107f9fecd - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  20:     0x7fff9b6a799c - _pthread_body
  21:     0x7fff9b6a7919 - _pthread_start
stack backtrace:
   1:        0x107f9ebb8 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x107fa0daf - panicking::default_handler::_<closure>::closure.41800
   3:        0x107fa082f - panicking::default_handler::haa11ce011d688073GWx
   4:        0x107f8b9b4 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x107f8be5e - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x107f9e1d7 - rust_begin_unwind
   7:        0x107fc5740 - panicking::panic_fmt::he5f9c513e9167673LnK
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:688
   8:        0x107789549 - api::RenderApi::add_display_list::h9c8dff3db95ad97bJHb
   9:        0x106a33da6 - webrender_helpers::StackingContext.WebRenderStackingContextConverter::convert_to_webrender::hf65854b25150004bOdx
  10:        0x106aa35f3 - webrender_helpers::DisplayItem.WebRenderDisplayItemConverter::convert_to_webrender::h8049ad97dde53199nhx
  11:        0x106aa226f - webrender_helpers::Box<DisplayList>.WebRenderDisplayListConverter::convert_to_webrender::hf7e8dec913d33989nfx
  12:        0x106a33d57 - webrender_helpers::StackingContext.WebRenderStackingContextConverter::convert_to_webrender::hf65854b25150004bOdx
  13:        0x106aa35f3 - webrender_helpers::DisplayItem.WebRenderDisplayItemConverter::convert_to_webrender::h8049ad97dde53199nhx
  14:        0x106aa226f - webrender_helpers::Box<DisplayList>.WebRenderDisplayListConverter::convert_to_webrender::hf7e8dec913d33989nfx
  15:        0x106a33d57 - webrender_helpers::StackingContext.WebRenderStackingContextConverter::convert_to_webrender::hf65854b25150004bOdx
  16:        0x106a8f0bf - layout_thread::LayoutThread::perform_post_main_layout_passes::h2432abf606c57c67Ear
  17:        0x106a04db4 - layout_thread::LayoutThread::perform_post_style_recalc_layout_passes::h6a718355ed85f0c147q
  18:        0x106a0b2ba - layout_thread::LayoutThread::handle_reflow::hb77a0d746fab5f65COq
  19:        0x1069f24ae - layout_thread::LayoutThread::handle_request_helper::hdfa3c6c5e15c3dfbSrq
  20:        0x1069d7431 - layout_thread::LayoutThread::handle_request::hc16ed0d4edae377fhmq
  21:        0x10699f8ca - sys_common::unwind::try::try_fn::h10583997351341377314
  22:        0x107f9dff8 - __rust_try
  23:        0x107f9aeae - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  24:        0x1069a084a - boxed::F.FnBox<A>::call_box::h7559661375126348099
  25:        0x107f9fecd - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  26:     0x7fff9b6a799c - _pthread_body
  27:     0x7fff9b6a7919 - _pthread_start
stack backtrace:
thread 'LayoutWorker worker 1/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:thread 'thread 'LayoutWorker worker 2/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:688
ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:688
688
thread 'LayoutWorker worker 3/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:688
   1:        0x107f9ebb8 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x107fa0daf - panicking::default_handler::_<closure>::closure.41800
   3:        0x107fa082f - panicking::default_handler::haa11ce011d688073GWx
   4:        0x107f8b9b4 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x107f8be5e - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x107f9e1d7 - rust_begin_unwind
   7:        0x107fc5740 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x10741ffb7 - paint_thread::WorkerThread::main::h1f33011f9833d7f4zco
   9:        0x10741e02b - sys_common::unwind::try::try_fn::h8834067971183654828
  10:        0x107f9dff8 - __rust_try
  11:        0x107f9aeae - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  12:        0x10741e5c6 - boxed::F.FnBox<A>::call_box::h11412307701203464889
  13:        0x107f9fecd - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  14:     0x7fff9b6a799c - _pthread_body
  15:     0x7fff9b6a7919 - _pthread_start
stack backtrace:
   1:        0x107f9ebb8 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x107fa0daf - panicking::default_handler::_<closure>::closure.41800
   3:        0x107fa082f - panicking::default_handler::haa11ce011d688073GWx
   4:        0x107f8b9b4 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x107f8be5e - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x107f9e1d7 - rust_begin_unwind
   7:        0x107fc5740 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x10741ffb7 - paint_thread::WorkerThread::main::h1f33011f9833d7f4zco
   9:        0x10741e02b - sys_common::unwind::try::try_fn::h8834067971183654828
  10:        0x107f9dff8 - __rust_try
  11:        0x107f9aeae - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  12:        0x10741e5c6 - boxed::F.FnBox<A>::call_box::h11412307701203464889
  13:        0x107f9fecd - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  14:     0x7fff9b6a799c - _pthread_body
  15:     0x7fff9b6a7919 - _pthread_start
stack backtrace:
   1:        0x107f9ebb8 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x107fa0daf - panicking::default_handler::_<closure>::closure.41800
   3:        0x107fa082f - panicking::default_handler::haa11ce011d688073GWx
   4:        0x107f8b9b4 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x107f8be5e - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x107f9e1d7 - rust_begin_unwind
   7:        0x107fc5740 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x10741ffb7 - paint_thread::WorkerThread::main::h1f33011f9833d7f4zco
   9:        0x10741e02b - sys_common::unwind::try::try_fn::h8834067971183654828
  10:        0x107f9dff8 - __rust_try
  11:        0x107f9aeae - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  12:        0x10741e5c6 - boxed::F.FnBox<A>::call_box::h11412307701203464889
  13:        0x107f9fecd - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  14:     0x7fff9b6a799c - _pthread_body
  15:     0x7fff9b6a7919 - _pthread_start
stack backtrace:
   1:        0x107f9ebb8 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x107fa0daf - panicking::default_handler::_<closure>::closure.41800
   3:        0x107fa082f - panicking::default_handler::haa11ce011d688073GWx
   4:        0x107f8b9b4 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x107f8be5e - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x107f9e1d7 - rust_begin_unwind
   7:        0x107fc5740 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x106e90fed - dom::node::OpaqueStyleAndLayoutData::dispose::he573f803fd4d198fbzZ
   9:        0x106b3b808 - dom..node..Node::drop.135924::h0738048cd066ae62
  10:        0x106b3b73a - dom::bindings::codegen::Bindings::CommentBinding::_finalize::h5a14a82b9eb2daf5OmD
  11:        0x107e4f15e - _ZN2js2gc5Arena8finalizeI8JSObjectEEmPNS_6FreeOpENS0_9AllocKindEm
  12:        0x107e08704 - _ZL14FinalizeArenasPN2js6FreeOpEPPNS_2gc11ArenaHeaderERNS2_15SortedArenaListENS2_9AllocKindERNS_11SliceBudgetENS2_10ArenaLists14KeepArenasEnumE
  13:        0x107e0be85 - _ZN2js2gc10ArenaLists30queueForegroundObjectsForSweepEPNS_6FreeOpE
  14:        0x107e11c93 - _ZN2js2gc9GCRuntime22beginSweepingZoneGroupEv
  15:        0x107e128f6 - _ZN2js2gc9GCRuntime15beginSweepPhaseEb
  16:        0x107e1501c - _ZN2js2gc9GCRuntime23incrementalCollectSliceERNS_11SliceBudgetEN2JS8gcreason6ReasonE
  17:        0x107e15724 - _ZN2js2gc9GCRuntime7gcCycleEbRNS_11SliceBudgetEN2JS8gcreason6ReasonE
  18:        0x107e15bfe - _ZN2js2gc9GCRuntime7collectEbNS_11SliceBudgetEN2JS8gcreason6ReasonE
  19:        0x107dc6afa - _ZN2js14DestroyContextEP9JSContextNS_18DestroyContextModeE
  20:        0x1079d60d1 - rust::Runtime.Drop::drop::he9a44b687b1d0465mKi
  21:        0x106f6fca8 - script_thread..ScriptThread::drop.167774::h387993027f24bb71
  22:        0x106f6b4e6 - sys_common::unwind::try::try_fn::h6700430166590279951
  23:        0x107f9dff8 - __rust_try
  24:        0x107f9aeae - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  25:        0x106f6bce1 - boxed::F.FnBox<A>::call_box::h4377540654281972257
  26:        0x107f9fecd - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  27:     0x7fff9b6a799c - _pthread_body
  28:     0x7fff9b6a7919 - _pthread_start
thread panicked while panicking. aborting.stack backtrace:
```

**Comment by paulrouget** [comment]
Happens with many websites.

Sometimes, it crashes with:

```
1 thread '<unnamed>' panicked at 'assertion failed: clipped_pos_rect.size.height.fract() == 0.0', /Users/paul/git/servo-webrender/../webrender/src/batch_builder.rs:150
```

**Comment by glennw** [comment]
@paulrouget I've temporarily disabled the asserts so that you can work (they should have been debug asserts anyway). We can leave this issue open until I have time to investigate the root cause though.
