### ISSUE TITLE
Crashing after loading 2 iframes with WebRender

### ISSUE THREAD

**Issue by paulrouget** [glennw/webrender#157]
I don't have any reduced test case yet. Working on it.

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:330
stack backtrace:
   1:        0x10ecc5738 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x10ecc792f - panicking::default_handler::_<closure>::closure.41800
   3:        0x10ecc73af - panicking::default_handler::haa11ce011d688073GWx
   4:        0x10ecb2534 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x10ecb29de - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x10ecc4d57 - rust_begin_unwind
   7:        0x10ecec2c0 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x10ecec5bc - panicking::panic::h4d53392809a8cd58imK
   9:        0x10e0402c9 - frame::RenderTarget::collect_and_sort_visible_batches::hc8bfc950ef4ad87dRDj
  10:        0x10e053900 - frame::Frame::build::hc2b5f0c528f3282diqk
  11:        0x10e0a60c5 - render_backend::RenderBackend::render::h7080e83362199b576Xo
  12:        0x10e072379 - render_backend::RenderBackend::run::h4b98f1d876540ce9hOo
  13:        0x10e0c5504 - sys_common::unwind::try::try_fn::h14387719792712352988
  14:        0x10ecc4b78 - __rust_try
  15:        0x10ecc1a2e - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  16:        0x10e0c664a - boxed::F.FnBox<A>::call_box::h9518937930668500773
  17:        0x10ecc6a4d - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  18:     0x7fff9242c99c - _pthread_body
  19:     0x7fff9242c919 - _pthread_start
thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) }', ../src/libcore/result.rs:688
stack backtrace:
   1:        0x10ecc5738 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x10ecc792f - panicking::default_handler::_<closure>::closure.41800
   3:        0x10ecc73af - panicking::default_handler::haa11ce011d688073GWx
   4:        0x10ecb2534 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x10ecb29de - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x10ecc4d57 - rust_begin_unwind
   7:        0x10ecec2c0 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x10e4b00c9 - api::RenderApi::add_display_list::h122a8f4edc42c167JHb
   9:        0x10d758546 - webrender_helpers::StackingContext.WebRenderStackingContextConverter::convert_to_webrender::h6e53fbe2ff03d125aex
  10:        0x10d7c7dd3 - webrender_helpers::DisplayItem.WebRenderDisplayItemConverter::convert_to_webrender::h4f2746533ab07044Jhx
  11:        0x10d7c6a4f - webrender_helpers::Box<DisplayList>.WebRenderDisplayListConverter::convert_to_webrender::h61fba242ff7fd4b0Jfx
  12:        0x10d7584f7 - webrender_helpers::StackingContext.WebRenderStackingContextConverter::convert_to_webrender::h6e53fbe2ff03d125aex
  13:        0x10d7c7dd3 - webrender_helpers::DisplayItem.WebRenderDisplayItemConverter::convert_to_webrender::h4f2746533ab07044Jhx
  14:        0x10d7c6a4f - webrender_helpers::Box<DisplayList>.WebRenderDisplayListConverter::convert_to_webrender::h61fba242ff7fd4b0Jfx
  15:        0x10d7584f7 - webrender_helpers::StackingContext.WebRenderStackingContextConverter::convert_to_webrender::h6e53fbe2ff03d125aex
  16:        0x10d7c7dd3 - webrender_helpers::DisplayItem.WebRenderDisplayItemConverter::convert_to_webrender::h4f2746533ab07044Jhx
  17:        0x10d7c6a4f - webrender_helpers::Box<DisplayList>.WebRenderDisplayListConverter::convert_to_webrender::h61fba242ff7fd4b0Jfx
  18:        0x10d7584f7 - webrender_helpers::StackingContext.WebRenderStackingContextConverter::convert_to_webrender::h6e53fbe2ff03d125aex
  19:        0x10d7c7dd3 - webrender_helpers::DisplayItem.WebRenderDisplayItemConverter::convert_to_webrender::h4f2746533ab07044Jhx
  20:        0x10d7c6a4f - webrender_helpers::Box<DisplayList>.WebRenderDisplayListConverter::convert_to_webrender::h61fba242ff7fd4b0Jfx
  21:        0x10d7584f7 - webrender_helpers::StackingContext.WebRenderStackingContextConverter::convert_to_webrender::h6e53fbe2ff03d125aex
  22:        0x10d7c7dd3 - webrender_helpers::DisplayItem.WebRenderDisplayItemConverter::convert_to_webrender::h4f2746533ab07044Jhx
  23:        0x10d7c6a4f - webrender_helpers::Box<DisplayList>.WebRenderDisplayListConverter::convert_to_webrender::h61fba242ff7fd4b0Jfx
  24:        0x10d7584f7 - webrender_helpers::StackingContext.WebRenderStackingContextConverter::convert_to_webrender::h6e53fbe2ff03d125aex
  25:        0x10d7c7dd3 - webrender_helpers::DisplayItem.WebRenderDisplayItemConverter::convert_to_webrender::h4f2746533ab07044Jhx
  26:        0x10d7c6a4f - webrender_helpers::Box<DisplayList>.WebRenderDisplayListConverter::convert_to_webrender::h61fba242ff7fd4b0Jfx
  27:        0x10d7584f7 - webrender_helpers::StackingContext.WebRenderStackingContextConverter::convert_to_webrender::h6e53fbe2ff03d125aex
  28:        0x10d7b389f - layout_thread::LayoutThread::perform_post_main_layout_passes::hcaeea298f28b9d0d0ar
  29:        0x10d729554 - layout_thread::LayoutThread::perform_post_style_recalc_layout_passes::h45ec4e504c055255q8q
  30:        0x10d7b58d0 - layout_thread::LayoutThread::tick_animations::hca014a87de70550dc6q
  31:        0x10d711873 - layout_thread::LayoutThread::handle_request_helper::h2545ed8c4e831956esq
  32:        0x10d6fbed9 - layout_thread::LayoutThread::handle_request::hc4ed1141d8f5f73dDmq
  33:        0x10d6c404a - sys_common::unwind::try::try_fn::h16847173986951035809
  34:        0x10ecc4b78 - __rust_try
  35:        0x10ecc1a2e - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  36:        0x10d6c4fca - boxed::F.FnBox<A>::call_box::h3078129605127003304
  37:        0x10ecc6a4d - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  38:     0x7fff9242c99c - _pthread_body
  39:     0x7fff9242c919 - _pthread_start
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'assertion failed: !self.Document().needs_reflow() || self.window_size.get().is_none()', /Users/paul/git/servo-webrender/components/script/dom/window.rsthread 'PaintThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:688
:thread 'LayoutWorker worker 1/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', stack backtrace:
../src/libcore/result.rs:688
thread 'LayoutWorker worker 2/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError1013', 
../src/libcore/result.rs:688
thread 'LayoutWorker worker 3/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:688
thread 'Constellation' panicked at 'unable to find pipeline - this is a bug', ../src/libcore/option.rs:298
thread 'PaintThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) }', ../src/libcore/result.rs:688
   1:        0x10ecc5738 - thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("Unknown Mach error: 46") }) }', sys::backtrace::../src/libcore/result.rs:688
tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x10ecc792f - panicking::default_handler::_<closure>::closure.41800
   3:        0x10ecc73af - panicking::default_handler::haa11ce011d688073GWx
   4:        0x10ecb2534 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x10ecb29de - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x10ecc4d57 - rust_begin_unwind
   7:        0x10ecec2c0 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x10def337b - paint_thread::PaintThread<C>::start::h14920655049683345238
   9:        0x10dee62d2 - sys_common::unwind::try::try_fn::h2651601220024240560
  10:        0x10ecc4b78 - __rust_try
  11:        0x10ecc1a2e - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  12:        0x10dee6dba - boxed::F.FnBox<A>::call_box::h17013775538103610657
  13:        0x10ecc6a4d - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  14:     0x7fff9242c99c - _pthread_body
  15:     0x7fff9242c919 - _pthread_start
stack backtrace:
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:688
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:688
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:688
   1:        0x10ecc5738 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x10ecc792f - panicking::default_handler::_<closure>::closure.41800
   3:        0x10ecc73af - panicking::default_handler::haa11ce011d688073GWx
   4:        0x10ecb2534 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x10ecb29de - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x10ecc4d57 - rust_begin_unwind
   7:        0x10ecec2c0 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x10d6e966c - sys_common::unwind::try::try_fn::h16822593756666436252
   9:        0x10ecc4b78 - __rust_try
  10:        0x10ecc1a2e - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  11:        0x10d6ea5f7 - boxed::F.FnBox<A>::call_box::h1110295214265204133
  12:        0x10ecc6a4d - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  13:     0x7fff9242c99c - _pthread_body
  14:     0x7fff9242c919 - _pthread_start
stack backtrace:
   1:        0x10ecc5738 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x10ecc792f - panicking::default_handler::_<closure>::closure.41800
   3:        0x10ecc73af - panicking::default_handler::haa11ce011d688073GWx
   4:        0x10ecb2534 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x10d7caf54 - sys_common::unwind::begin_unwind::h404296098094245515
   6:        0x10dae788f - dom::window::Window::reflow::h69c1a6652d64886bVKc
   7:        0x10dafbe5c - dom::document::Document::run_the_animation_frame_callbacks::hfa00300515f5f5a5w2E
   8:        0x10dce33f8 - script_thread::ScriptThread::handle_msg_from_constellation::he0640e1726b46053sQh
   9:        0x10dce165e - script_thread::ScriptThread::handle_msgs::_<closure>::closure.169679
  10:        0x10dcca4df - script_thread::ScriptThread::handle_msgs::h268282795e499be4lFh
  11:        0x10dc91877 - sys_common::unwind::try::try_fn::h7478225447160613408
  12:        0x10ecc4b78 - __rust_try
  13:        0x10ecc1a2e - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  14:        0x10dc93301 - boxed::F.FnBox<A>::call_box::h5881412153639161957
  15:        0x10ecc6a4d - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  16:     0x7fff9242c99c - _pthread_body
  17:     0x7fff9242c919 - _pthread_start
stack backtrace:
   1:        0x10ecc5738 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x10ecc792f - panicking::default_handler::_<closure>::closure.41800
   3:        0x10ecc73af - panicking::default_handler::haa11ce011d688073GWx
   4:        0x10ecb2534 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x10ecb29de - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x10ecc4d57 - rust_begin_unwind
   7:        0x10ecec2c0 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x10d6e966c - sys_common::unwind::try::try_fn::h16822593756666436252
   9:        0x10ecc4b78 - __rust_try
  10:        0x10ecc1a2e - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  11:        0x10d6ea5f7 - boxed::F.FnBox<A>::call_box::h1110295214265204133
  12:        0x10ecc6a4d - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  13:     0x7fff9242c99c - _pthread_body
  14:     0x7fff9242c919 - _pthread_start
stack backtrace:
   1:        0x10ecc5738 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x10ecc792f - panicking::default_handler::_<closure>::closure.41800
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:688
   3:        0x10ecc73af - panicking::default_handler::haa11ce011d688073GWx
   4:        0x10ecb2534 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x10ecb29de - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x10ecc4d57 - rust_begin_unwind
   7:        0x10ecec2c0 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x10d6e966c - sys_common::unwind::try::try_fn::h16822593756666436252
   9:        0x10ecc4b78 - __rust_try
  10:        0x10ecc1a2e - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  11:        0x10d6ea5f7 - boxed::F.FnBox<A>::call_box::h1110295214265204133
  12:        0x10ecc6a4d - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  13:     0x7fff9242c99c - _pthread_body
  14:     0x7fff9242c919 - _pthread_start
stack backtrace:
   1:        0x10ecc5738 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x10ecc792f - panicking::default_handler::_<closure>::closure.41800
   3:        0x10ecc73af - panicking::default_handler::haa11ce011d688073GWx
   4:        0x10ecb2534 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x10ecb29de - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x10ecc4d57 - rust_begin_unwind
   7:        0x10ecec2c0 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x10d5ba6c7 - constellation::Constellation<LTF, STF>::handle_failure_msg::h15610954865508890704
   9:        0x10d539465 - constellation::Constellation<LTF, STF>::handle_request::h10275348153301879876
  10:        0x10d524377 - export::compositing::constellation::Constellation<LTF, STF>::start::_<closure>::closure.23883
  11:        0x10d523c19 - sys_common::unwind::try::try_fn::h15516516964861941524
  12:        0x10ecc4b78 - __rust_try
  13:        0x10ecc1a2e - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  14:        0x10d525a8a - boxed::F.FnBox<A>::call_box::h13598726564070865733
  15:        0x10ecc6a4d - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  16:     0x7fff9242c99c - _pthread_body
  17:     0x7fff9242c919 - _pthread_start
stack backtrace:
thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:688
   1:        0x10ecc5738 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x10ecc792f - panicking::default_handler::_<closure>::closure.41800
   3:        0x10ecc73af - panicking::default_handler::haa11ce011d688073GWx
   4:        0x10ecb2534 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x10ecb29de - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x10ecc4d57 - rust_begin_unwind
   7:        0x10ecec2c0 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x10dee68ab - sys_common::unwind::try::try_fn::h2651601220024240560
   9:        0x10ecc4b78 - __rust_try
  10:        0x10ecc1a2e - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  11:        0x10dee6dba - boxed::F.FnBox<A>::call_box::h17013775538103610657
  12:        0x10ecc6a4d - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  13:     0x7fff9242c99c - _pthread_body
  14:     0x7fff9242c919 - _pthread_start
stack backtrace:
   1:        0x10ecc5738 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x10ecc792f - panicking::default_handler::_<closure>::closure.41800
   3:        0x10ecc73af - panicking::default_handler::haa11ce011d688073GWx
   4:        0x10ecb2534 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x10ecb29de - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x10ecc4d57 - rust_begin_unwind
   7:        0x10ecec2c0 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x10d731a1a - layout_thread::LayoutThread::exit_now::ha53401f267e2cd62jCq
   9:        0x10d712173 - layout_thread::LayoutThread::handle_request_helper::h2545ed8c4e831956esq
  10:        0x10d6fbe5a - layout_thread::LayoutThread::handle_request::hc4ed1141d8f5f73dDmq
  11:        0x10d6c404a - sys_common::unwind::try::try_fn::h16847173986951035809
  12:        0x10ecc4b78 - __rust_try
  13:        0x10ecc1a2e - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  14:        0x10d6c4fca - boxed::F.FnBox<A>::call_box::h3078129605127003304
  15:        0x10ecc6a4d - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  16:     0x7fff9242c99c - _pthread_body
  17:     0x7fff9242c919 - _pthread_start
stack backtrace:
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:688
   1:        0x10ecc5738 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x10ecc792f - panicking::default_handler::_<closure>::closure.41800
   3:        0x10ecc73af - panicking::default_handler::haa11ce011d688073GWx
   4:        0x10ecb2534 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x10ecb29de - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x10ecc4d57 - rust_begin_unwind
   7:        0x10ecec2c0 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x10e146b07 - paint_thread::WorkerThread::main::he80f4671a25a37bfxco
   9:        0x10e144b7b - sys_common::unwind::try::try_fn::h8194431729755483626
  10:        0x10ecc4b78 - __rust_try
  11:        0x10ecc1a2e - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  12:        0x10e145116 - boxed::F.FnBox<A>::call_box::h2340907832130704384
  13:        0x10ecc6a4d - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  14:     0x7fff9242c99c - _pthread_body
  15:     0x7fff9242c919 - _pthread_start
stack backtrace:
   1:        0x10ecc5738 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x10ecc792f - panicking::default_handler::_<closure>::closure.41800
   3:        0x10ecc73af - panicking::default_handler::haa11ce011d688073GWx
   4:        0x10ecb2534 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x10ecb29de - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x10ecc4d57 - rust_begin_unwind
   7:        0x10ecec2c0 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x10e146b07 - paint_thread::WorkerThread::main::he80f4671a25a37bfxco
   9:        0x10e144b7b - sys_common::unwind::try::try_fn::h8194431729755483626
  10:        0x10ecc4b78 - __rust_try
  11:        0x10ecc1a2e - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  12:        0x10e145116 - boxed::F.FnBox<A>::call_box::h2340907832130704384
  13:        0x10ecc6a4d - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  14:     0x7fff9242c99c - _pthread_body
  15:     0x7fff9242c919 - _pthread_start
stack backtrace:
   1:        0x10ecc5738 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x10ecc792f - panicking::default_handler::_<closure>::closure.41800
   3:        0x10ecc73af - panicking::default_handler::haa11ce011d688073GWx
   4:        0x10ecb2534 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x10ecb29de - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x10ecc4d57 - rust_begin_unwind
   7:        0x10ecec2c0 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x10e146b07 - paint_thread::WorkerThread::main::he80f4671a25a37bfxco
   9:        0x10e144b7b - sys_common::unwind::try::try_fn::h8194431729755483626
  10:        0x10ecc4b78 - __rust_try
  11:        0x10ecc1a2e - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  12:        0x10e145116 - boxed::F.FnBox<A>::call_box::h2340907832130704384
  13:        0x10ecc6a4d - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  14:     0x7fff9242c99c - _pthread_body
  15:     0x7fff9242c919 - _pthread_start
stack backtrace:
   1:        0x10ecc5738 - sys::backtrace::tracing::imp::write::hdd549f07f7745d62xZt
   2:        0x10ecc792f - panicking::default_handler::_<closure>::closure.41800
   3:        0x10ecc73af - panicking::default_handler::haa11ce011d688073GWx
   4:        0x10ecb2534 - sys_common::unwind::begin_unwind_inner::h5fdd923b078bc2aaz2s
   5:        0x10ecb29de - sys_common::unwind::begin_unwind_fmt::hca18532ec345b882F1s
   6:        0x10ecc4d57 - rust_begin_unwind
   7:        0x10ecec2c0 - panicking::panic_fmt::he5f9c513e9167673LnK
   8:        0x10dbb863d - dom::node::OpaqueStyleAndLayoutData::dispose::hecd4d43e30e92265HQZ
   9:        0x10d85fcf8 - dom..node..Node::drop.135999::h59ce0c8c46dd1f6e
  10:        0x10d8d17db - dom..element..Element::drop.139619::h633b4873187e1faf
  11:        0x10d9269e6 - dom::bindings::codegen::Bindings::HTMLHtmlElementBinding::_finalize::h1f16e6ed44f9c106vRe
  12:        0x10eb75cde - _ZN2js2gc5Arena8finalizeI8JSObjectEEmPNS_6FreeOpENS0_9AllocKindEm
  13:        0x10eb2f284 - _ZL14FinalizeArenasPN2js6FreeOpEPPNS_2gc11ArenaHeaderERNS2_15SortedArenaListENS2_9AllocKindERNS_11SliceBudgetENS2_10ArenaLists14KeepArenasEnumE
  14:        0x10eb32a05 - _ZN2js2gc10ArenaLists30queueForegroundObjectsForSweepEPNS_6FreeOpE
  15:        0x10eb38813 - _ZN2js2gc9GCRuntime22beginSweepingZoneGroupEv
  16:        0x10eb39476 - _ZN2js2gc9GCRuntime15beginSweepPhaseEb
  17:        0x10eb3bb9c - _ZN2js2gc9GCRuntime23incrementalCollectSliceERNS_11SliceBudgetEN2JS8gcreason6ReasonE
  18:        0x10eb3c2a4 - _ZN2js2gc9GCRuntime7gcCycleEbRNS_11SliceBudgetEN2JS8gcreason6ReasonE
  19:        0x10eb3c77e - _ZN2js2gc9GCRuntime7collectEbNS_11SliceBudgetEN2JS8gcreason6ReasonE
  20:        0x10eaed67a - _ZN2js14DestroyContextEP9JSContextNS_18DestroyContextModeE
  21:        0x10e6fcc51 - rust::Runtime.Drop::drop::he9a44b687b1d0465mKi
  22:        0x10dc972c8 - script_thread..ScriptThread::drop.167879::h5817f4887e9b2c5e
  23:        0x10dc92b06 - sys_common::unwind::try::try_fn::h7478225447160613408
  24:        0x10ecc4b78 - __rust_try
  25:        0x10ecc1a2e - sys_common::unwind::try::inner_try::h3da6140ab038e3437Ys
  26:        0x10dc93301 - boxed::F.FnBox<A>::call_box::h5881412153639161957
  27:        0x10ecc6a4d - sys::thread::Thread::new::thread_start::hf2e9bf34aeeb6fa0acx
  28:     0x7fff9242c99c - _pthread_body
  29:     0x7fff9242c919 - _pthread_start
thread panicked while panicking. aborting.stack backtrace:
```

**Comment by paulrouget** [comment]
It crashes here: https://github.com/glennw/webrender/commit/b21317a8fb69d43c00e14f7d1503919aef78abbb#diff-8c1748e0d20c7a39978ef7656d9f39f4L245

But I see you just changed this code… updating and rebuilding…

**Comment by paulrouget** [comment]
This apparently only happens if I use `--resolution 1200x800`.

**Comment by paulrouget** [comment]
Crashes here: https://github.com/glennw/webrender/blob/b21317a8fb69d43c00e14f7d1503919aef78abbb/src/frame.rs#L249

**Comment by glennw** [comment]
Don't worry about a test case - I know what causes this. For now, change the let texture_size = 2048; line above to 4096 or even 8192. That's just a temporary workaround - I'll fix this properly in the next few days.
