### ISSUE TITLE
Crash 'Didn't find a cached resource with that ID!'

### ISSUE THREAD

**Issue by paulrouget** [glennw/webrender#163]
Happens every time I load http://github.com/servo in servo:

```
./mach run -r -- -w http://github.com/servo
```

```
thread '<unnamed>' panicked at 'Didn't find a cached resource with that ID!', ../src/libcore/option.rs:704
stack backtrace:
   1:        0x1090a2158 - sys::backtrace::tracing::imp::write::h268482af15af0a80Y8t
   2:        0x1090a42b5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42271
   3:        0x1090a3eb6 - panicking::default_handler::h97bc664f7e2bfeb5Ocy
   4:        0x10908f5c6 - sys_common::unwind::begin_unwind_inner::h98c0975c9b6b2fa0Zbt
   5:        0x10908fa7e - sys_common::unwind::begin_unwind_fmt::h3fbfbcdbf87c23935at
   6:        0x1090a1767 - rust_begin_unwind
   7:        0x1090c6ae0 - panicking::panic_fmt::h27f7225e08792f40qYL
   8:        0x1090ce395 - option::expect_failed::hd2f3bf5ae63612e0zsO
   9:        0x108994ffd - resource_cache::ResourceCache::get_raster::hef626877b5e80240bip
  10:        0x1089949d7 - batch_builder::BatchBuilder<'a>::add_complex_clipped_rectangle::hbe01c43b96ed445d17a
  11:        0x1089d7e4f - node_compiler::AABBTreeNode.NodeCompiler::compile::hdbbd2da5ea027db9e6n
  12:        0x1089d74ff - F.FnBox::call_box::h13262016776754699915
  13:        0x108a5de49 - sys_common::unwind::try::try_fn::h9508438189223046798
  14:        0x1090a16fb - __rust_try
  15:        0x10909e693 - sys_common::unwind::inner_try::h3c719a7bb47af1af18s
  16:        0x108a5fdcf - boxed::F.FnBox<A>::call_box::h1234570727023147477
  17:        0x1090a353d - sys::thread::Thread::new::thread_start::hbf136943ebd5e19atrx
  18:     0x7fff9242c99c - _pthread_body
  19:     0x7fff9242c919 - _pthread_start
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
stack backtrace:
   1:        0x1090a2158 - sys::backtrace::tracing::imp::write::h268482af15af0a80Y8t
   2:        0x1090a42b5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42271
   3:        0x1090a3eb6 - panicking::default_handler::h97bc664f7e2bfeb5Ocy
   4:        0x10908f5c6 - sys_common::unwind::begin_unwind_inner::h98c0975c9b6b2fa0Zbt
   5:        0x10908fa7e - sys_common::unwind::begin_unwind_fmt::h3fbfbcdbf87c23935at
   6:        0x1090a1767 - rust_begin_unwind
   7:        0x1090c6ae0 - panicking::panic_fmt::h27f7225e08792f40qYL
   8:        0x108a65d25 - result::unwrap_failed::h13587443107209132209
   9:        0x108a650a6 - Scope<'pool, 'scope>::join_all::h6082a71387c0f3b2aga
  10:        0x1089ccd54 - frame::Frame::build::h4b2acf17b342c0fe6nk
  11:        0x108a2b025 - render_backend::RenderBackend::render::h9a4862e2bcd1c70dtVo
  12:        0x1089e730b - render_backend::RenderBackend::run::h6f2991724828dc86ULo
  13:        0x108a46ed5 - sys_common::unwind::try::try_fn::h12786140589539203898
  14:        0x1090a16fb - __rust_try
  15:        0x10909e693 - sys_common::unwind::inner_try::h3c719a7bb47af1af18s
  16:        0x108a47f3a - boxed::F.FnBox<A>::call_box::h14427120922120626088
  17:        0x1090a353d - sys::thread::Thread::new::thread_start::hbf136943ebd5e19atrx
  18:     0x7fff9242c99c - _pthread_body
  19:     0x7fff9242c919 - _pthread_start
thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) }', ../src/libcore/result.rs:746
stack backtrace:
   1:        0x1090a2158 - sys::backtrace::tracing::imp::write::h268482af15af0a80Y8t
   2:        0x1090a42b5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42271
   3:        0x1090a3eb6 - panicking::default_handler::h97bc664f7e2bfeb5Ocy
   4:        0x10908f5c6 - sys_common::unwind::begin_unwind_inner::h98c0975c9b6b2fa0Zbt
   5:        0x10908fa7e - sys_common::unwind::begin_unwind_fmt::h3fbfbcdbf87c23935at
   6:        0x1090a1767 - rust_begin_unwind
   7:        0x1090c6ae0 - panicking::panic_fmt::h27f7225e08792f40qYL
   8:        0x108a80f79 - result::unwrap_failed::h11280939636593810237
   9:        0x108a98b0c - api::RenderApi::add_display_list::ha0710cf823fb7e482Ib
  10:        0x107baf42c - webrender_helpers::StackingContext.WebRenderStackingContextConverter::convert_to_webrender::h7751b488e8e322f0DKx
  11:        0x107c14339 - webrender_helpers::DisplayItem.WebRenderDisplayItemConverter::convert_to_webrender::h8b1eacc0309d4ea8cOx
  12:        0x107c1309f - webrender_helpers::Box<DisplayList>.WebRenderDisplayListConverter::convert_to_webrender::ha50cde7b5b1fa21dcMx
  13:        0x107baf3dd - webrender_helpers::StackingContext.WebRenderStackingContextConverter::convert_to_webrender::h7751b488e8e322f0DKx
  14:        0x107c14339 - webrender_helpers::DisplayItem.WebRenderDisplayItemConverter::convert_to_webrender::h8b1eacc0309d4ea8cOx
  15:        0x107c1309f - webrender_helpers::Box<DisplayList>.WebRenderDisplayListConverter::convert_to_webrender::ha50cde7b5b1fa21dcMx
  16:        0x107baf3dd - webrender_helpers::StackingContext.WebRenderStackingContextConverter::convert_to_webrender::h7751b488e8e322f0DKx
  17:        0x107c01653 - layout_thread::LayoutThread::perform_post_main_layout_passes::ha2703ee31939d080zrr
  18:        0x107b772c7 - layout_thread::LayoutThread::perform_post_style_recalc_layout_passes::hc95c05c249753567Zor
  19:        0x107b7caf4 - layout_thread::LayoutThread::handle_reflow::he4863ec2ceff3350x5q
  20:        0x107b5f450 - layout_thread::LayoutThread::handle_request_helper::h2e51af2fced8e9d3CIq
  21:        0x107b45382 - layout_thread::LayoutThread::handle_request::h4c10aa9f9378e5841Cq
  22:        0x107b106ba - sys_common::unwind::try::try_fn::h15435063139969083263
  23:        0x1090a16fb - __rust_try
  24:        0x10909e693 - sys_common::unwind::inner_try::h3c719a7bb47af1af18s
  25:        0x107b11581 - boxed::F.FnBox<A>::call_box::h2333798665030695924
  26:        0x1090a353d - sys::thread::Thread::new::thread_start::hbf136943ebd5e19atrx
  27:     0x7fff9242c99c - _pthread_body
  28:     0x7fff9242c919 - _pthread_start
thread 'thread 'LayoutWorker worker 3/3' panicked at 'thread 'thread 'called `Result::unwrap()` on an `Err` value: RecvError', PaintThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }LayoutWorker worker 1/3LayoutWorker worker 2/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorcalled `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746', ../src/libcore/result.rs../src/libcore/result.rs', ../src/libcore/result.rs
stack backtrace:
::746:746
746

thread 'Constellation' panicked at 'unable to find pipeline - this is a bug', ../src/libcore/option.rs:704
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:746
   1:        0x1090a2158 - sys::backtrace::tracing::imp::write::h268482af15af0a80Y8t
   2:        0x1090a42b5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42271
   3:        0x1090a3eb6 - panicking::default_handler::h97bc664f7e2bfeb5Ocy
   4:        0x10908f5c6 - sys_common::unwind::begin_unwind_inner::h98c0975c9b6b2fa0Zbt
   5:        0x10908fa7e - sys_common::unwind::begin_unwind_fmt::h3fbfbcdbf87c23935at
   6:        0x1090a1767 - rust_begin_unwind
   7:        0x1090c6ae0 - panicking::panic_fmt::h27f7225e08792f40qYL
   8:        0x107c27ab5 - result::unwrap_failed::h2233387100194087648
   9:        0x107c6eec4 - paint_thread::PaintThread<C>::start::h16034862843767342259
  10:        0x107c6204d - sys_common::unwind::try::try_fn::h17758900513200347130
  11:        0x1090a16fb - __rust_try
  12:        0x10909e693 - sys_common::unwind::inner_try::h3c719a7bb47af1af18s
  13:        0x107c62a51 - boxed::F.FnBox<A>::call_box::h10217729106636372389
  14:        0x1090a353d - sys::thread::Thread::new::thread_start::hbf136943ebd5e19atrx
  15:     0x7fff9242c99c - _pthread_body
  16:     0x7fff9242c919 - _pthread_start
stack backtrace:
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:746

   1:        0x1090a2158 - sys::backtrace::tracing::imp::write::h268482af15af0a80Y8t
   2:        0x1090a42b5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42271
   3:        0x1090a3eb6 - panicking::default_handler::h97bc664f7e2bfeb5Ocy
   4:        0x10908f5c6 - sys_common::unwind::begin_unwind_inner::h98c0975c9b6b2fa0Zbt
   5:        0x10908fa7e - sys_common::unwind::begin_unwind_fmt::h3fbfbcdbf87c23935at
   6:        0x1090a1767 - rust_begin_unwind
   7:        0x1090c6ae0 - panicking::panic_fmt::h27f7225e08792f40qYL
   8:        0x107b35285 - result::unwrap_failed::h5559368555008630596
   9:        0x107b34776 - sys_common::unwind::try::try_fn::h17767510098955593324
  10:        0x1090a16fb - __rust_try
  11:        0x10909e693 - sys_common::unwind::inner_try::h3c719a7bb47af1af18s
  12:        0x107b34ef1 - boxed::F.FnBox<A>::call_box::h16761730589695629546
  13:        0x1090a353d - sys::thread::Thread::new::thread_start::hbf136943ebd5e19atrx
  14:     0x7fff9242c99c - _pthread_body
  15:     0x7fff9242c919 - _pthread_start
stack backtrace:
   1:        0x1090a2158 - sys::backtrace::tracing::imp::write::h268482af15af0a80Y8t
   2:        0x1090a42b5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42271
   3:        0x1090a3eb6 - panicking::default_handler::h97bc664f7e2bfeb5Ocy
   4:        0x10908f5c6 - sys_common::unwind::begin_unwind_inner::h98c0975c9b6b2fa0Zbt
   5:        0x10908fa7e - sys_common::unwind::begin_unwind_fmt::h3fbfbcdbf87c23935at
   6:        0x1090a1767 - rust_begin_unwind
   7:        0x1090c6ae0 - panicking::panic_fmt::h27f7225e08792f40qYL
   8:        0x107b35285 - result::unwrap_failed::h5559368555008630596
   9:        0x107b34776 - sys_common::unwind::try::try_fn::h17767510098955593324
  10:        0x1090a16fb - __rust_try
  11:        0x10909e693 - sys_common::unwind::inner_try::h3c719a7bb47af1af18s
  12:        0x107b34ef1 - boxed::F.FnBox<A>::call_box::h16761730589695629546
  13:        0x1090a353d - sys::thread::Thread::new::thread_start::hbf136943ebd5e19atrx
  14:     0x7fff9242c99c - _pthread_body
  15:     0x7fff9242c919 - _pthread_start
stack backtrace:
   1:        0x1090a2158 - sys::backtrace::tracing::imp::write::h268482af15af0a80Y8t
   2:        0x1090a42b5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42271
   3:        0x1090a3eb6 - panicking::default_handler::h97bc664f7e2bfeb5Ocy
   4:        0x10908f5c6 - sys_common::unwind::begin_unwind_inner::h98c0975c9b6b2fa0Zbt
   5:        0x10908fa7e - sys_common::unwind::begin_unwind_fmt::h3fbfbcdbf87c23935at
   6:        0x1090a1767 - rust_begin_unwind
   7:        0x1090c6ae0 - panicking::panic_fmt::h27f7225e08792f40qYL
   8:        0x107b35285 - result::unwrap_failed::h5559368555008630596
   9:        0x107b34776 - sys_common::unwind::try::try_fn::h17767510098955593324
  10:        0x1090a16fb - __rust_try
  11:        0x10909e693 - sys_common::unwind::inner_try::h3c719a7bb47af1af18s
  12:        0x107b34ef1 - boxed::F.FnBox<A>::call_box::h16761730589695629546
  13:        0x1090a353d - sys::thread::Thread::new::thread_start::hbf136943ebd5e19atrx
  14:     0x7fff9242c99c - _pthread_body
  15:     0x7fff9242c919 - _pthread_start
stack backtrace:
   1:        0x1090a2158 - sys::backtrace::tracing::imp::write::h268482af15af0a80Y8t
   2:        0x1090a42b5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42271
   3:        0x1090a3eb6 - panicking::default_handler::h97bc664f7e2bfeb5Ocy
   4:        0x10908f5c6 - sys_common::unwind::begin_unwind_inner::h98c0975c9b6b2fa0Zbt
   5:        0x10908fa7e - sys_common::unwind::begin_unwind_fmt::h3fbfbcdbf87c23935at
   6:        0x1090a1767 - rust_begin_unwind
   7:        0x1090c6ae0 - panicking::panic_fmt::h27f7225e08792f40qYL
   8:        0x1090ce395 - option::expect_failed::hd2f3bf5ae63612e0zsO
   9:        0x1079ef4f1 - constellation::Constellation<LTF, STF>::handle_failure_msg::h4958220644789437469
  10:        0x107962029 - constellation::Constellation<LTF, STF>::handle_request::h2583114810960791304
  11:        0x10794fb37 - export::compositing::constellation::Constellation<LTF, STF>::start::_$u7b$$u7b$closure$u7d$$u7d$::closure.24446
  12:        0x10794f3c9 - sys_common::unwind::try::try_fn::h6420113767769976744
  13:        0x1090a16fb - __rust_try
  14:        0x10909e693 - sys_common::unwind::inner_try::h3c719a7bb47af1af18s
  15:        0x1079513c1 - boxed::F.FnBox<A>::call_box::h1691856731935225294
  16:        0x1090a353d - sys::thread::Thread::new::thread_start::hbf136943ebd5e19atrx
  17:     0x7fff9242c99c - _pthread_body
  18:     0x7fff9242c919 - _pthread_start
stack backtrace:
   1:        0x1090a2158 - sys::backtrace::tracing::imp::write::h268482af15af0a80Y8t
   2:        0x1090a42b5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42271
   3:        0x1090a3eb6 - panicking::default_handler::h97bc664f7e2bfeb5Ocy
   4:        0x10908f5c6 - sys_common::unwind::begin_unwind_inner::h98c0975c9b6b2fa0Zbt
   5:        0x10908fa7e - sys_common::unwind::begin_unwind_fmt::h3fbfbcdbf87c23935at
   6:        0x1090a1767 - rust_begin_unwind
   7:        0x1090c6ae0 - panicking::panic_fmt::h27f7225e08792f40qYL
   8:        0x107fa7617 - result::unwrap_failed::h7188770798299934690
   9:        0x108077f9f - dom::node::OpaqueStyleAndLayoutData::dispose::h3cd3f38f0bd436b0030
  10:        0x108078147 - dom::node::Node::teardown::hde43020265ed94ccZe1
  11:        0x108078249 - dom::node::Node::teardown::hde43020265ed94ccZe1
  12:        0x108124689 - dom::window::Window::clear_js_runtime::h31fcf46fa7cfd964HUd
  13:        0x1081ae590 - script_thread::shut_down_layout::h0697b9482715d32dIkk
  14:        0x108193243 - script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::closure.170202
  15:        0x10817dbd8 - script_thread::ScriptThread::handle_msgs::h5814a31d760d4b3ct0i
  16:        0x108146eb7 - sys_common::unwind::try::try_fn::h12649174468245035598
  17:        0x1090a16fb - __rust_try
  18:        0x10909e693 - sys_common::unwind::inner_try::h3c719a7bb47af1af18s
  19:        0x10814854a - boxed::F.FnBox<A>::call_box::h5752158415730817369
  20:        0x1090a353d - sys::thread::Thread::new::thread_start::hbf136943ebd5e19atrx
  21:     0x7fff9242c99c - _pthread_body
  22:     0x7fff9242c919 - _pthread_start
stack backtrace:
   1:        0x1090a2158 - sys::backtrace::tracing::imp::write::h268482af15af0a80Y8t
   2:        0x1090a42b5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42271
   3:        0x1090a3eb6 - panicking::default_handler::h97bc664f7e2bfeb5Ocy
   4:        0x10908f5c6 - sys_common::unwind::begin_unwind_inner::h98c0975c9b6b2fa0Zbt
   5:        0x10908fa7e - sys_common::unwind::begin_unwind_fmt::h3fbfbcdbf87c23935at
   6:        0x1090a1767 - rust_begin_unwind
   7:        0x1090c6ae0 - panicking::panic_fmt::h27f7225e08792f40qYL
   8:        0x1082d29b5 - result::unwrap_failed::h6576405179137328736
   9:        0x1082cd6a7 - paint_thread::WorkerThread::main::he80f4671a25a37bfxco
  10:        0x1082ca078 - sys_common::unwind::try::try_fn::h12407554919505963314
  11:        0x1090a16fb - __rust_try
  12:        0x10909e693 - sys_common::unwind::inner_try::h3c719a7bb47af1af18s
  13:        0x1082ca600 - boxed::F.FnBox<A>::call_box::h10024689754618462265
  14:        0x1090a353d - sys::thread::Thread::new::thread_start::hbf136943ebd5e19atrx
  15:     0x7fff9242c99c - _pthread_body
  16:     0x7fff9242c919 - _pthread_start
stack backtrace:
   1:        0x1090a2158 - sys::backtrace::tracing::imp::write::h268482af15af0a80Y8t
   2:        0x1090a42b5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42271
   3:        0x1090a3eb6 - panicking::default_handler::h97bc664f7e2bfeb5Ocy
   4:        0x10908f5c6 - sys_common::unwind::begin_unwind_inner::h98c0975c9b6b2fa0Zbt
   5:        0x10908fa7e - sys_common::unwind::begin_unwind_fmt::h3fbfbcdbf87c23935at
   6:        0x1090a1767 - rust_begin_unwind
   7:        0x1090c6ae0 - panicking::panic_fmt::h27f7225e08792f40qYL
   8:        0x1082d29b5 - result::unwrap_failed::h6576405179137328736
   9:        0x1082cd6a7 - paint_thread::WorkerThread::main::he80f4671a25a37bfxco
  10:        0x1082ca078 - sys_common::unwind::try::try_fn::h12407554919505963314
  11:        0x1090a16fb - __rust_try
  12:        0x10909e693 - sys_common::unwind::inner_try::h3c719a7bb47af1af18s
  13:        0x1082ca600 - boxed::F.FnBox<A>::call_box::h10024689754618462265
  14:        0x1090a353d - sys::thread::Thread::new::thread_start::hbf136943ebd5e19atrx
  15:     0x7fff9242c99c - _pthread_body
  16:     0x7fff9242c919 - _pthread_start
stack backtrace:
   1:        0x1090a2158 - sys::backtrace::tracing::imp::write::h268482af15af0a80Y8t
   2:        0x1090a42b5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42271
   3:        0x1090a3eb6 - panicking::default_handler::h97bc664f7e2bfeb5Ocy
   4:        0x10908f5c6 - sys_common::unwind::begin_unwind_inner::h98c0975c9b6b2fa0Zbt
   5:        0x10908fa7e - sys_common::unwind::begin_unwind_fmt::h3fbfbcdbf87c23935at
   6:        0x1090a1767 - rust_begin_unwind
   7:        0x1090c6ae0 - panicking::panic_fmt::h27f7225e08792f40qYL
   8:        0x1082d29b5 - result::unwrap_failed::h6576405179137328736
   9:        0x1082cd6a7 - paint_thread::WorkerThread::main::he80f4671a25a37bfxco
  10:        0x1082ca078 - sys_common::unwind::try::try_fn::h12407554919505963314
  11:        0x1090a16fb - __rust_try
  12:        0x10909e693 - sys_common::unwind::inner_try::h3c719a7bb47af1af18s
  13:        0x1082ca600 - boxed::F.FnBox<A>::call_box::h10024689754618462265
  14:        0x1090a353d - sys::thread::Thread::new::thread_start::hbf136943ebd5e19atrx
  15:     0x7fff9242c99c - _pthread_body
  16:     0x7fff9242c919 - _pthread_start
thread 'ImageCacheThread' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) }', ../src/libcore/result.rs:746
stack backtrace:
   1:        0x1090a2158 - sys::backtrace::tracing::imp::write::h268482af15af0a80Y8t
   2:        0x1090a42b5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42271
   3:        0x1090a3eb6 - panicking::default_handler::h97bc664f7e2bfeb5Ocy
   4:        0x10908f5c6 - sys_common::unwind::begin_unwind_inner::h98c0975c9b6b2fa0Zbt
   5:        0x10908fa7e - sys_common::unwind::begin_unwind_fmt::h3fbfbcdbf87c23935at
   6:        0x1090a1767 - rust_begin_unwind
   7:        0x1090c6ae0 - panicking::panic_fmt::h27f7225e08792f40qYL
   8:        0x108a80f79 - result::unwrap_failed::h11280939636593810237
   9:        0x108a98822 - api::RenderApi::add_image::h5af0cdea34c8e50fBHb
  10:        0x1085e9f6e - image_cache_thread::ImageCache::complete_load::hf562057fd3d12e32umc
  11:        0x1085c4096 - image_cache_thread::ImageCache::run::hf7259cb8eaea33b8cfc
  12:        0x1085fd86e - sys_common::unwind::try::try_fn::h13365323490457168969
  13:        0x1090a16fb - __rust_try
  14:        0x10909e693 - sys_common::unwind::inner_try::h3c719a7bb47af1af18s
  15:        0x1085fe99a - boxed::F.FnBox<A>::call_box::h5439146165892437764
  16:        0x1090a353d - sys::thread::Thread::new::thread_start::hbf136943ebd5e19atrx
  17:     0x7fff9242c99c - _pthread_body
  18:     0x7fff9242c919 - _pthread_start
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:746
stack backtrace:
   1:        0x1090a2158 - sys::backtrace::tracing::imp::write::h268482af15af0a80Y8t
   2:        0x1090a42b5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42271
   3:        0x1090a3eb6 - panicking::default_handler::h97bc664f7e2bfeb5Ocy
   4:        0x10908f5c6 - sys_common::unwind::begin_unwind_inner::h98c0975c9b6b2fa0Zbt
   5:        0x10908fa7e - sys_common::unwind::begin_unwind_fmt::h3fbfbcdbf87c23935at
   6:        0x1090a1767 - rust_begin_unwind
   7:        0x1090c6ae0 - panicking::panic_fmt::h27f7225e08792f40qYL
   8:        0x1085f5f67 - result::unwrap_failed::h14532895690339850851
   9:        0x1085f2c24 - image_cache_thread::ImageCache::request_image::_$u7b$$u7b$closure$u7d$$u7d$::closure.33841
  10:        0x108aabe34 - sys_common::unwind::try::try_fn::h16159413210957910413
  11:        0x1090a16fb - __rust_try
  12:        0x10909e693 - sys_common::unwind::inner_try::h3c719a7bb47af1af18s
  13:        0x108aae5ec - boxed::F.FnBox<A>::call_box::h1997465058112654723
  14:        0x1090a353d - sys::thread::Thread::new::thread_start::hbf136943ebd5e19atrx
  15:     0x7fff9242c99c - _pthread_body
  16:     0x7fff9242c919 - _pthread_start
```

**Comment by glennw** [comment]
@paulrouget I pushed a fix for this just a few mins ago (and that site seems to work ok for me with the change). Could you pull the latest and confirm it fixes it for you?

**Comment by paulrouget** [comment]
It works. Thank you.
